include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Style
    prefer_single_quotes: true
    require_trailing_commas: true
    always_use_package_imports: true
    directives_ordering: true
    sort_child_properties_last: true
    unnecessary_await_in_return: true

    # Safety
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true

    # Documentation
    public_member_api_docs: false

    # Types
    always_declare_return_types: true
    prefer_final_locals: true
    avoid_unused_constructor_parameters: true
